site_name: GitOps
site_description: Documentation for GitOps repository
site_author: s3lcsum
site_url: https://s3lcsum.github.io/gitops/

# Repository
repo_name: s3lcsum/gitops
repo_url: https://github.com/s3lcsum/gitops

# Navigation
nav:
  - "Home": index.md
  - "ADR001: Traefik over NPM": adr/adr001-traefik-over-npm.md
  - "ADR002: Authentik over ZITADEL": adr/adr002-authentik-over-zitadel.md
  - "GP001: Add Docker Stack": golden-paths/gp001-add-docker-stack.md
  - "GP002: Add Terraform Module (Gitea mirrors)": golden-paths/gp002-add-terraform-module-gitea-mirrors.md
  - "RB001: Initialize Vault": runbooks/rb001-initialize-vault.md
  - "RB007: Stalwart SMTP Setup": runbooks/rb007-smtp-stalwart-setup.md

watch:
  - docs
