apiVersion: v2
name: tailscale
description: Tailscale Kubernetes Operator
type: application
version: 0.1.0
appVersion: "1.58.2"

dependencies:
- name: tailscale-operator
  version: "1.90.8"
  repository: https://pkgs.tailscale.com/helmcharts
