# https://github.com/s3lcsum/gitops/blob/main/stacks/warracker/compose.yaml

services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    container_name: warracker
    restart: unless-stopped
    env_file:
      - /opt/warracker/warracker.env
    environment:
      FRONTEND_URL: https://warracker.lake.dominiksiejak.pl
      APP_BASE_URL: https://warracker.lake.dominiksiejak.pl
    volumes:
      - uploads:/data/uploads
    networks:
      - proxy
      - database
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
  database:
    external: true

volumes:
  uploads:


