# https://github.com/s3lcsum/gitops/blob/main/stacks/n8n/compose.yaml


services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - /opt/n8n/n8n.env
    environment:
      N8N_METRICS: true
      N8N_RUNNERS_ENABLED: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_EDITOR_BASE_URL: https://nodemation.lake.dominiksiejak.pl
      WEBHOOK_URL: https://nodemation.lake.dominiksiejak.pl
    volumes:
      - config:/home/node/.n8n
    networks:
      - proxy
      - database
      - metrics
    labels:
      traefik.enable: true
      traefik.http.services.n8n.loadbalancer.server.port: 5678
      traefik.http.routers.n8n.rule: Host(`nodemation.lake.dominiksiejak.pl`) || Host(`nodemation.hello.dominiksiejak.pl`)

networks:
  proxy:
    external: true
  database:
    external: true
  metrics:
    external: true

volumes:
  config:
