apiVersion: v2
name: kyverno
description: Kyverno policy engine for Kubernetes
type: application
version: 0.1.0
appVersion: "1.12.0"

dependencies:
- name: kyverno
  version: "3.6.0"
  repository: https://kyverno.github.io/kyverno/
